### ISSUE TITLE
Getting Error working with Single End Bam file 

### ISSUE THREAD

**Issue by svermai** [LihuaJulieZhu/GUIDEseq#3]
Hi @LihuaJulieZhu 
1. There is one issue which is I'm not able to figure out in the bioconductor package (https://www.bioconductor.org/packages/release/bioc/vignettes/GUIDEseq/inst/doc/GUIDEseq.pdf) , It takes the paired end reads bam file works properly but for single end reads bam file it fails with error :-
'_Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 0, 1_'
So tried each step individually then I understood that problem lies at initial stage : getUniqueCleavageEvents(bamfile, umifile, n.cores.max =1).
Some where i found **GUIDEseq:::importBAMAlignments(file="input.bam")** to check the whether it loads the bam file or not so for single end bam it give error.
Can you please provide me some information how to use single end bam with guideseq package.

2. I'm having demultiplex fastq file from which bam file is prepared to generate the UMI file I'm using [UMIbarcode_python2.py](https://github.com/umasstr/GS-Preprocess/blob/master/src/UMIbarcode_python2.py)  From GS-Preprocess github repo somewhere mention in your workshop youtube link. Is it good to use this script because it is already demultiplexed ? 

Thank you

**Comment by LihuaJulieZhu** [comment]
Hi Shubham,


GUIDEseq package only supports paired end data since most of quality filters such as max.paired.distance and concordant.strand, and the extraction of cleavage site relies on the paired end information.


Best regards,
Julie

From: Shubham Verma ***@***.***>
Date: Tuesday, October 11, 2022 at 6:23 AM
To: LihuaJulieZhu/GUIDEseq ***@***.***>
Cc: Zhu, Lihua (Julie) ***@***.***>, Mention ***@***.***>
Subject: [LihuaJulieZhu/GUIDEseq] Getting Error working with Single End Bam file (Issue #3)

Hi @LihuaJulieZhu<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLihuaJulieZhu&data=05%7C01%7Cjulie.zhu%40umassmed.edu%7Cd83be6268eaf47df08fa08daab7263db%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C638010806136219337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=paqxYk%2BxTky6S26DScKnIISe7VoSi93axejVIJUaRWc%3D&reserved=0>
There is one issue which is I'm not able to figure out in the bioconductor package (https://www.bioconductor.org/packages/release/bioc/vignettes/GUIDEseq/inst/doc/GUIDEseq.pdf<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.bioconductor.org%2Fpackages%2Frelease%2Fbioc%2Fvignettes%2FGUIDEseq%2Finst%2Fdoc%2FGUIDEseq.pdf&data=05%7C01%7Cjulie.zhu%40umassmed.edu%7Cd83be6268eaf47df08fa08daab7263db%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C638010806136219337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pqnpnUHeGANAkK8peXaA%2FeQ1kOE24%2FA1Gf31uISN%2BDY%3D&reserved=0>) , It takes the paired end bam file works properly but for single end bam file it fails with error :-
'Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 0, 1'
So tried each step individually then I understood that problem lies at initial stage : getUniqueCleavageEvents(bamfile, umifile, n.cores.max =1).
Some where i found GUIDEseq:::importBAMAlignments(file="input.bam") to check the whether it loads the bam file or not so for single end bam it give error.
Can you please provide me some information how to use single end bam with guideseq package.

**Comment by svermai** [comment]
Thank a lot for your quick response @LihuaJulieZhu  really appreciate it , small request can you please let me know if this script https://github.com/umasstr/GS-Preprocess/blob/master/src/UMIbarcode_python2.py is good to go for pair end fastq file to generate UMI file required in Guideseq package. The reason I'm not able use perl script https://mccb.umassmed.edu/GUIDE-seq/getUmi.pl, Is I'm already having demultiplex fastq file and not having Illumina-format SampleSheet along barcode length.

**Comment by LihuaJulieZhu** [comment]
You are very welcome, Shubham!

Yes, I recommend you use GS-Preprocess to generate all the input files for GUIDEseq package.
https://github.com/umasstr/GS-Preprocess/

I am ccing Dr. Tomás Rodriguez, the main developer of the GS-Preprocess to address your question regarding https://github.com/umasstr/GS-Preprocess/blob/master/src/UMIbarcode_python2.py<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fumasstr%2FGS-Preprocess%2Fblob%2Fmaster%2Fsrc%2FUMIbarcode_python2.py&data=05%7C01%7Cjulie.zhu%40umassmed.edu%7C8fdcc74234274ae0e22308daab98776b%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C638010968572882205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Muc3BnVfNoPDPX%2BpMLzKjw52c8hpDwUKpEZw6Ty0tm4%3D&reserved=0>.

Best,
Julie

From: Shubham Verma ***@***.***>
Date: Tuesday, October 11, 2022 at 10:54 AM
To: LihuaJulieZhu/GUIDEseq ***@***.***>
Cc: Zhu, Lihua (Julie) ***@***.***>, Mention ***@***.***>
Subject: Re: [LihuaJulieZhu/GUIDEseq] Getting Error working with Single End Bam file (Issue #3)

Thank a lot for your quick response @LihuaJulieZhu<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLihuaJulieZhu&data=05%7C01%7Cjulie.zhu%40umassmed.edu%7C8fdcc74234274ae0e22308daab98776b%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C638010968572882205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TG63D5y2h8vwwr6wIRofI2Tj2Bq3ZypNl3tJMSbmrmA%3D&reserved=0> really appreciate it , small request can you please let me know if this script https://github.com/umasstr/GS-Preprocess/blob/master/src/UMIbarcode_python2.py<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fumasstr%2FGS-Preprocess%2Fblob%2Fmaster%2Fsrc%2FUMIbarcode_python2.py&data=05%7C01%7Cjulie.zhu%40umassmed.edu%7C8fdcc74234274ae0e22308daab98776b%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C638010968572882205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Muc3BnVfNoPDPX%2BpMLzKjw52c8hpDwUKpEZw6Ty0tm4%3D&reserved=0> is good to go for pair end fastq file to generate UMI file required in Guideseq package. The reason I'm not able use perl script https://mccb.umassmed.edu/GUIDE-seq/getUmi.pl, Is I'm already having demultiplex fastq file and not having Illumina-format SampleSheet along barcode length.

**Comment by LihuaJulieZhu** [comment]
Hi Shubham,

Please feel free to contact me. The pipeline is for GUIDEseq experiments run on Miniseq and Nextseq. It also assumes a 9nt UMI. Let me know if we can help!

Tomás

**Comment by svermai** [comment]
Thank for the help Julie !

**Comment by LihuaJulieZhu** [comment]
You are very welcome, Shubham!

Best wishes,

Julie
________________________________
